<a href="https://colab.research.google.com/github/plumwiserim/Data-Analysis/blob/main/Class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 데이터 분석을 위한 파이썬 라이브러리

#### TIOBE Index
#### TIOBE Index for C
#### TIOBE Index for Java
#### TIOBE Index for Python

#### Python

- 세계적으로 가장 대중적인 언어 중 하나
- 높은 생산성, 확장성
  - 다양한 라이브러리 제공
- 높은 범용성
  - 일반 어플리케이션
  - 웹 프로그래밍
  - 데이터 분석
  - 인공지능
  - GUI 개발

#### Python 기반 라이브러리 소개
- 데이터 분석 및 인공지능 활용을 위한 파이썬 기반 라이브러리
  - Pandas : 행과 열을 가지는 2차원 데이터 분석을 위한 라이브러리
  - NumPy : 행렬이나 대규모 다차원 데이터 분석을 위한 라이브러리
  - Matplotlib, Seaborn : 데이터 분석을 위한 시각화 라이브러리
  - SciPy, Statsmodels : 파이썬 기반의 통계 분석을 위한 파이썬 라이브러리
  - Scikit-learn : 파이썬 기반의 대표적인 머신러닝 라이브러리

#### 과정 소개
- 데이터 분석을 위한 Pandas 라이브러리의 이해와 활용
- 데이터 분석을 위한 NumPy 라이브러리의 이해와 활용
- 데이터 시각화를 위한 Matplotlib 라이브러리의 이해와 활용
- 파이썬 기반 데이터 분석 실습 프로젝트

### NumPy 라이브러리 소개

#### Python 기반 라이브러리

#### NumPy 라이브러리 소개
- Numerical Python의 줄임말
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- https://numpy.org/

#### N차원(N-Dimension)
- 1차원 - 선
- 2차원 - 면
- 3차원 - 공간
- 4차원 ...
- 5차원 ...
- ...
- N차원

#### 2차원 데이터

#### 이미지 데이터

- 흑백 이미지 데이터는 몇 차원일까요? 2차원 데이터 (높이 X 너비) 
  - 이미지는 수많은 픽셀로 구성되어 있음
  - 흑백(gray-scale) 이미지는 각 픽셀의 밝기 값을 0~255 사이로 표현한 이미지


- 컬러 이미지 데이터는 몇 차원일까요? 3차원 데이터(높이 X 너비 X 컬러채널)

#### 영상 데이터
- 영상 데이터는 몇 차원일까요? 4차원 데이터 (프레임 X 높이 X 너비 X 컬러채널)
  - 연속된 형태의 수많은 이미지들이 모인 형태

#### ndarray
- NumPy는 다양한 차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- NumPy는 ndarray(N-Dimension Array)라는 핵심 자료구조를 제공함
  - 대규모 데이터 집합을 담을 수 있는 매우 빠르고 유연한 핵심 자료구조

#### NumPy의 주요 특징

- much easier to learn and use
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
-> 연산 속도가 빠르고, 메모리를 효율적으로 사용
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
-> 반복문 작성 필요 없이 N차원의 데이터 배열을 바로 연산할 수 있음

#### NumPy 를 배운다는 것은?

- 다양한 차원의 데이터를 ndarray에 저장, 추가, 수정, 삭제할 수 있고
- ndarray 에 저장된 데이터들을 연산, 조회, 정렬할 수 있고
- 다양한 데이터들을 원하는 뷰로 결합하여 활용할 수 있는
- 파이썬 기반으로 만들어진 도구 사용법을 배우는 과정

#### NumPy 시작하기
- NumPy 실습환경(이미 설치되어 있음)
- NumPy 라이브러리 설치

> conda install numpy

> pip install numpy

### NumPy의 자료구조 : ndarray

- 다양한 차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- NumPy는 ndarray(N-Dimensional Array)라는 핵심 자료구조를 제공함
  - 대규모 데이터 집합을 담을 수 있는 매우 빠르고 유연한 핵심 자료구조

#### 1차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

2차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

#### 3차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

#### ndarray의 구성요소 : 축(axis)
- 배열의 각 차원(dimension)
- 축(axis)
- 차원(축)의 개수 : ndim = 1
- shape : (10,)
- 차원(축)의 개수 : ndim = 2
- shape : (3, 4)
- 차원(축)의 개수 : ndim = 3
- shape : (3, 4, 3)


#### ndarray 의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)
- 차원(축)의 개수 (ndim)

#### NumPy 시작하기

- NumPy 라이브러리 호출 및 별칭(alias) 지정 (np.XXX)

In [2]:
import numpy as np

- NumPy 에서 제공하는 함수 호출시 alias 이용해서 호출 가능

In [ ]:
print(np.__version__)

1.19.5


#### ndarray의 구성요소
- ndarray의 주요 속성
  - 형태 : ndarray.shape
  - 원소의 수 : ndarray.size
  - 저장된 데이터의 타입 : ndarray.dtype
  - 배열의 차원(축)의 수 : ndarray.ndim

#### ndarray의 생성

In [ ]:
# ndarray 생성
data = [10, 20, 30]
arr = np.array(data)

# 생성한 ndarray 의 속성 출력
print('\nCreate 1D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 1D Array
[10 20 30]
type =  <class 'numpy.ndarray'>
shape: (3,), size: 3, dtype: int64, dimension: 1


np.array(object, dtype)
- 입력된 데이터(object)를 인자로 받아 ndarray를 생성하는 함수
- Parameters : 
  - object : ndarray에 저장할 데이터 
  - dtype : 배열의 데이터 타입, 기본 값은 None, 생략가능

#### 2차원 ndarray의 생성

In [3]:
# 2차원 ndarray 생성
data = [[1,2,3],[4,5,6]]
arr = np.array(data)

# 생성한 ndarray의 속성 출력
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 2D Array
[[1 2 3]
 [4 5 6]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### dtype = float 를 지정하면?

In [4]:
# 2차원 ndarray 생성
data = [[1,2,3],[4,5,6]]
arr = np.array(data, dtype = float)

# 생성한 ndarray의 속성 출력
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 2D Array
[[1. 2. 3.]
 [4. 5. 6.]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: float64, dimension: 2


#### 3차원 ndarray의 생성

In [5]:
# 3차원 ndarray 생성
data = [[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
arr = np.array(data, dtype = float)

#생성한 ndarray의 속성 출력
print('\nCreate 3D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 3D Array
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
type =  <class 'numpy.ndarray'>
shape: (2, 2, 3), size: 12, dtype: float64, dimension: 3


### NumPy 자료구조 : ndarray의 생성

#### NumPy.array()

np.array(object,dtype)
- 입력된 데이터(object)를 인자로 받아 ndarray를 생성하는 함수
- Parameters : 
  - object : ndarray에 저장할 데이터 
  - dtype : 배열의 데이터 타입, 기본 값은 None, 생략가능

#### ndarray 의 생성
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- ...

#### NumPy.arange()

np.arange((start), stop, (step))

- 파이썬의 range()와 동일하게 연속된 데이터를 생성하는 함수

range((start), stop, (step))

range(1,5)

range(1, 5, 2)

range(5.0)

- Parameters : 
  - start : 생성할 시작 값으로 생략 가능함. 생략되면 0부터 생성됨.
  - stop : 생성되는 마지막 값으로 해당 값은 포함되지 않음.
  - step : 생성시 값들의 간격, 생략 가능

- np.arange()를 통한 ndarray 생성하기

In [7]:
import numpy as np

def printinfo(arr):
  print(arr)
  print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

#np.arange()를 통한 ndarray 생성
arr = np.arange(2, 10)
print('\n Create ndarray by np.arange()')
printinfo(arr)


 Create ndarray by np.arange()
[2 3 4 5 6 7 8 9]
shape: (8,), size: 8, dtype: int64, dimension: 1


#### ndarray의 생성
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- ...

#### NumPy.zeros()

np.zeros(shape, dtype = float)

- 지정된 크기(shape)만큼 배열을 생성하고, 모든 요소를 0으로 초기화
- 데이터 타입(dtype)은 입력하지 않으면 기본 float 타입으로 생성됨
- Parameters : 
  - shape : 생성할 ndarray의 크기로 튜플() 형태로 저장해야 함
  - dtype : 배열의 데이터 타입, 기본값은 float, 생략가능

- np.zeros()를 통한 ndarray 생성하기 (1)

In [8]:
# np.zeros() 를 통한 ndarray 생성
arr = np.zeros(5)
print('\n Create ndarray by np.zeros()')
printinfo(arr)


 Create ndarray by np.zeros()
[0. 0. 0. 0. 0.]
shape: (5,), size: 5, dtype: float64, dimension: 1


- np.zeros() 를 통한 ndarray 생성하기 (2)

In [10]:
# np.zeros() 를 통한 ndarray 생성
arr = np.zeros((3,4), dtype=int)
print('\n Create ndarray by np.zeros()')
printinfo(arr)


 Create ndarray by np.zeros()
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2


#### ndarray의 생성
- np.zeros(shape, dtype = float)
  - 지정된 크기 (shape) 만큼 배열을 생성하고, 모든 요소를 0으로 초기화
- np.ones(shape, dtype=float)
- np.full(shape, fill_value, dtype = None)
- np.empty()

#### NumPy.ones()

np.ones(shape, dtype = float)
- 지정된 크기(shape)의 배열을 생성하고, 모든 요소를 1로 초기화

In [11]:
# np.ones()를 통한 ndarray 생성
arr = np.ones((3,4))
print('\n Create ndarray by np.ones()')
printinfo(arr)


 Create ndarray by np.ones()
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (3, 4), size: 12, dtype: float64, dimension: 2


#### NumPy.full()

np.full(shape, fill_value, dtype=None)
- 지정된 크기(shape)의 배열을 생성하고, 모든 요소를 'fill_value'로 초기화

In [13]:
# np.full() 를 통한 ndarray 생성
arr = np.full((3,4),77)
print('\n Create ndarray by np.full()')
printinfo(arr)


 Create ndarray by np.full()
[[77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2


#### NumPy.empty()

np.empty(shape)
- 초기화되지 않은 상태로 지정된 shape만큼의 ndarray 생성
- 요소의 초기화 과정이 없어 배열 생성 비용이 가장 빠르고 저렴함
- 생성된 배열의 각 요소는 임의의 값이 저장되어 있음

In [14]:
arr = np.empty((2,2))
print('\n Create ndarray by np.empty()')
printinfo(arr)


 Create ndarray by np.empty()
[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]
shape: (2, 2), size: 4, dtype: float64, dimension: 2


#### *_like 함수

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

- np.zeros_like()
- np.ones_like()
- np.full_like()
- np.empty_like()

#### 샘플 데이터 생성

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

In [15]:
# sample 데이터 생성
data =  [[1,2,3],[4,5,6]]
sample = np.array(data)
print('\n Sample')
printinfo(sample)


 Sample
[[1 2 3]
 [4 5 6]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### Numpy.ones_like()

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

In [16]:
# ones_like()를 통한 ndarray 생성
one_array = np.ones_like(sample)
print('\n Create ndarray by np.ones_like()')
printinfo(one_array)


 Create ndarray by np.ones_like()
[[1 1 1]
 [1 1 1]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### Summary
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- np.*_like()
- ...

### NumPy 의 데이터 타입

#### NumPy 의 데이터 타입

- np.int64 : (64비트) 정수
- np.float64 : (64비트) 실수
- np.complex : 복소수
- np.bool : 불리언(True, False)
- np.object : 파이썬 객체
- np.str : 문자열

#### 정수형(Integer) 데이터 타입
- numpy.int는 음수와 양수를 표현하는 정수형 데이터 타입
- 뒤에 오는 숫자는 bit 의 개수를 의미함 (int8 -> 2^8 = 256 개 만큼의 정수의 표현이 가능)

#### 데이터 타입의 변경

방법1) ndarray 생성시 인자로 dtype 지정하는 방식

In [17]:
# 3차원 ndarray 생성
data = [[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
arr = np.array(data, dtype=float)

In [18]:
import numpy as np

#dtype 인자 지정을 통한 데이터 타입 변경
data = [1,2,3]
cpx_arr = np.array(data,dtype=np.complex)
str_arr = np.array(data,dtype=np.str)

print('Complex: ', cpx_arr)
print('String: ', str_arr)

Complex:  [1.+0.j 2.+0.j 3.+0.j]
String:  ['1' '2' '3']


방법2) ndarray.astype(dtype)
- ndarray에 저장된 데이터를 주어진 dtype으로 변환해서 반환함
- Paramters : 
  - dtype : 변경하고자 하는 배열의 데이터 타입

#### 샘플 데이터 생성

In [19]:
# 샘플 데이터 생성
origin = np.arange(1, 2, 0.2)
print('\nOriginal data')
print(origin)
print('dtype: ', origin.dtype)


Original data
[1.  1.2 1.4 1.6 1.8]
dtype:  float64


#### .astype() 을 통한 데이터 타입 변경
- astype() 을 활용한 데이터 타입 변경

In [20]:
# astype(dtype)을 활용한 데이터 타입 변경
result = origin.astype(int)
print('\nResult of astype(int)')
print(result)

print('\nOriginal data')
print(origin)


Result of astype(int)
[1 1 1 1 1]

Original data
[1.  1.2 1.4 1.6 1.8]
