<a href="https://colab.research.google.com/github/plumwiserim/Data-Analysis/blob/main/Class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 데이터 분석을 위한 파이썬 라이브러리

#### TIOBE Index
#### TIOBE Index for C
#### TIOBE Index for Java
#### TIOBE Index for Python

#### Python

- 세계적으로 가장 대중적인 언어 중 하나
- 높은 생산성, 확장성
  - 다양한 라이브러리 제공
- 높은 범용성
  - 일반 어플리케이션
  - 웹 프로그래밍
  - 데이터 분석
  - 인공지능
  - GUI 개발

#### Python 기반 라이브러리 소개
- 데이터 분석 및 인공지능 활용을 위한 파이썬 기반 라이브러리
  - Pandas : 행과 열을 가지는 2차원 데이터 분석을 위한 라이브러리
  - NumPy : 행렬이나 대규모 다차원 데이터 분석을 위한 라이브러리
  - Matplotlib, Seaborn : 데이터 분석을 위한 시각화 라이브러리
  - SciPy, Statsmodels : 파이썬 기반의 통계 분석을 위한 파이썬 라이브러리
  - Scikit-learn : 파이썬 기반의 대표적인 머신러닝 라이브러리

#### 과정 소개
- 데이터 분석을 위한 Pandas 라이브러리의 이해와 활용
- 데이터 분석을 위한 NumPy 라이브러리의 이해와 활용
- 데이터 시각화를 위한 Matplotlib 라이브러리의 이해와 활용
- 파이썬 기반 데이터 분석 실습 프로젝트

### NumPy 라이브러리 소개

#### Python 기반 라이브러리

#### NumPy 라이브러리 소개
- Numerical Python의 줄임말
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- https://numpy.org/

#### N차원(N-Dimension)
- 1차원 - 선
- 2차원 - 면
- 3차원 - 공간
- 4차원 ...
- 5차원 ...
- ...
- N차원

#### 2차원 데이터

#### 이미지 데이터

- 흑백 이미지 데이터는 몇 차원일까요? 2차원 데이터 (높이 X 너비) 
  - 이미지는 수많은 픽셀로 구성되어 있음
  - 흑백(gray-scale) 이미지는 각 픽셀의 밝기 값을 0~255 사이로 표현한 이미지


- 컬러 이미지 데이터는 몇 차원일까요? 3차원 데이터(높이 X 너비 X 컬러채널)

#### 영상 데이터
- 영상 데이터는 몇 차원일까요? 4차원 데이터 (프레임 X 높이 X 너비 X 컬러채널)
  - 연속된 형태의 수많은 이미지들이 모인 형태

#### ndarray
- NumPy는 다양한 차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- NumPy는 ndarray(N-Dimension Array)라는 핵심 자료구조를 제공함
  - 대규모 데이터 집합을 담을 수 있는 매우 빠르고 유연한 핵심 자료구조

#### NumPy의 주요 특징

- much easier to learn and use
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
-> 연산 속도가 빠르고, 메모리를 효율적으로 사용
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
-> 반복문 작성 필요 없이 N차원의 데이터 배열을 바로 연산할 수 있음

#### NumPy 를 배운다는 것은?

- 다양한 차원의 데이터를 ndarray에 저장, 추가, 수정, 삭제할 수 있고
- ndarray 에 저장된 데이터들을 연산, 조회, 정렬할 수 있고
- 다양한 데이터들을 원하는 뷰로 결합하여 활용할 수 있는
- 파이썬 기반으로 만들어진 도구 사용법을 배우는 과정

#### NumPy 시작하기
- NumPy 실습환경(이미 설치되어 있음)
- NumPy 라이브러리 설치

> conda install numpy

> pip install numpy

### NumPy의 자료구조 : ndarray

- 다양한 차원의 배열을 효율적으로 다룰 수 있는 라이브러리
- NumPy는 ndarray(N-Dimensional Array)라는 핵심 자료구조를 제공함
  - 대규모 데이터 집합을 담을 수 있는 매우 빠르고 유연한 핵심 자료구조

#### 1차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

2차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

#### 3차원 ndarray의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)

#### ndarray의 구성요소 : 축(axis)
- 배열의 각 차원(dimension)
- 축(axis)
- 차원(축)의 개수 : ndim = 1
- shape : (10,)
- 차원(축)의 개수 : ndim = 2
- shape : (3, 4)
- 차원(축)의 개수 : ndim = 3
- shape : (3, 4, 3)


#### ndarray 의 구성요소
- 형태(shape)
- 원소의 수(size)
- 저장된 데이터 타입(dtype)
- 차원(축)의 개수 (ndim)

#### NumPy 시작하기

- NumPy 라이브러리 호출 및 별칭(alias) 지정 (np.XXX)

In [2]:
import numpy as np

- NumPy 에서 제공하는 함수 호출시 alias 이용해서 호출 가능

In [ ]:
print(np.__version__)

1.19.5


#### ndarray의 구성요소
- ndarray의 주요 속성
  - 형태 : ndarray.shape
  - 원소의 수 : ndarray.size
  - 저장된 데이터의 타입 : ndarray.dtype
  - 배열의 차원(축)의 수 : ndarray.ndim

#### ndarray의 생성

In [ ]:
# ndarray 생성
data = [10, 20, 30]
arr = np.array(data)

# 생성한 ndarray 의 속성 출력
print('\nCreate 1D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 1D Array
[10 20 30]
type =  <class 'numpy.ndarray'>
shape: (3,), size: 3, dtype: int64, dimension: 1


np.array(object, dtype)
- 입력된 데이터(object)를 인자로 받아 ndarray를 생성하는 함수
- Parameters : 
  - object : ndarray에 저장할 데이터 
  - dtype : 배열의 데이터 타입, 기본 값은 None, 생략가능

#### 2차원 ndarray의 생성

In [3]:
# 2차원 ndarray 생성
data = [[1,2,3],[4,5,6]]
arr = np.array(data)

# 생성한 ndarray의 속성 출력
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 2D Array
[[1 2 3]
 [4 5 6]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### dtype = float 를 지정하면?

In [4]:
# 2차원 ndarray 생성
data = [[1,2,3],[4,5,6]]
arr = np.array(data, dtype = float)

# 생성한 ndarray의 속성 출력
print('\nCreate 2D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 2D Array
[[1. 2. 3.]
 [4. 5. 6.]]
type =  <class 'numpy.ndarray'>
shape: (2, 3), size: 6, dtype: float64, dimension: 2


#### 3차원 ndarray의 생성

In [5]:
# 3차원 ndarray 생성
data = [[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
arr = np.array(data, dtype = float)

#생성한 ndarray의 속성 출력
print('\nCreate 3D Array')
print(arr)
print('type = ', type(arr))
print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))


Create 3D Array
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
type =  <class 'numpy.ndarray'>
shape: (2, 2, 3), size: 12, dtype: float64, dimension: 3


### NumPy 자료구조 : ndarray의 생성

#### NumPy.array()

np.array(object,dtype)
- 입력된 데이터(object)를 인자로 받아 ndarray를 생성하는 함수
- Parameters : 
  - object : ndarray에 저장할 데이터 
  - dtype : 배열의 데이터 타입, 기본 값은 None, 생략가능

#### ndarray 의 생성
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- ...

#### NumPy.arange()

np.arange((start), stop, (step))

- 파이썬의 range()와 동일하게 연속된 데이터를 생성하는 함수

range((start), stop, (step))

range(1,5)

range(1, 5, 2)

range(5.0)

- Parameters : 
  - start : 생성할 시작 값으로 생략 가능함. 생략되면 0부터 생성됨.
  - stop : 생성되는 마지막 값으로 해당 값은 포함되지 않음.
  - step : 생성시 값들의 간격, 생략 가능

- np.arange()를 통한 ndarray 생성하기

In [7]:
import numpy as np

def printinfo(arr):
  print(arr)
  print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

#np.arange()를 통한 ndarray 생성
arr = np.arange(2, 10)
print('\n Create ndarray by np.arange()')
printinfo(arr)


 Create ndarray by np.arange()
[2 3 4 5 6 7 8 9]
shape: (8,), size: 8, dtype: int64, dimension: 1


#### ndarray의 생성
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- ...

#### NumPy.zeros()

np.zeros(shape, dtype = float)

- 지정된 크기(shape)만큼 배열을 생성하고, 모든 요소를 0으로 초기화
- 데이터 타입(dtype)은 입력하지 않으면 기본 float 타입으로 생성됨
- Parameters : 
  - shape : 생성할 ndarray의 크기로 튜플() 형태로 저장해야 함
  - dtype : 배열의 데이터 타입, 기본값은 float, 생략가능

- np.zeros()를 통한 ndarray 생성하기 (1)

In [8]:
# np.zeros() 를 통한 ndarray 생성
arr = np.zeros(5)
print('\n Create ndarray by np.zeros()')
printinfo(arr)


 Create ndarray by np.zeros()
[0. 0. 0. 0. 0.]
shape: (5,), size: 5, dtype: float64, dimension: 1


- np.zeros() 를 통한 ndarray 생성하기 (2)

In [10]:
# np.zeros() 를 통한 ndarray 생성
arr = np.zeros((3,4), dtype=int)
print('\n Create ndarray by np.zeros()')
printinfo(arr)


 Create ndarray by np.zeros()
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2


#### ndarray의 생성
- np.zeros(shape, dtype = float)
  - 지정된 크기 (shape) 만큼 배열을 생성하고, 모든 요소를 0으로 초기화
- np.ones(shape, dtype=float)
- np.full(shape, fill_value, dtype = None)
- np.empty()

#### NumPy.ones()

np.ones(shape, dtype = float)
- 지정된 크기(shape)의 배열을 생성하고, 모든 요소를 1로 초기화

In [11]:
# np.ones()를 통한 ndarray 생성
arr = np.ones((3,4))
print('\n Create ndarray by np.ones()')
printinfo(arr)


 Create ndarray by np.ones()
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (3, 4), size: 12, dtype: float64, dimension: 2


#### NumPy.full()

np.full(shape, fill_value, dtype=None)
- 지정된 크기(shape)의 배열을 생성하고, 모든 요소를 'fill_value'로 초기화

In [13]:
# np.full() 를 통한 ndarray 생성
arr = np.full((3,4),77)
print('\n Create ndarray by np.full()')
printinfo(arr)


 Create ndarray by np.full()
[[77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]]
shape: (3, 4), size: 12, dtype: int64, dimension: 2


#### NumPy.empty()

np.empty(shape)
- 초기화되지 않은 상태로 지정된 shape만큼의 ndarray 생성
- 요소의 초기화 과정이 없어 배열 생성 비용이 가장 빠르고 저렴함
- 생성된 배열의 각 요소는 임의의 값이 저장되어 있음

In [14]:
arr = np.empty((2,2))
print('\n Create ndarray by np.empty()')
printinfo(arr)


 Create ndarray by np.empty()
[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]
shape: (2, 2), size: 4, dtype: float64, dimension: 2


#### *_like 함수

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

- np.zeros_like()
- np.ones_like()
- np.full_like()
- np.empty_like()

#### 샘플 데이터 생성

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

In [15]:
# sample 데이터 생성
data =  [[1,2,3],[4,5,6]]
sample = np.array(data)
print('\n Sample')
printinfo(sample)


 Sample
[[1 2 3]
 [4 5 6]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### Numpy.ones_like()

지정된 배열과 shape이 같은 ndarray를 생성하는 *_like 함수

In [16]:
# ones_like()를 통한 ndarray 생성
one_array = np.ones_like(sample)
print('\n Create ndarray by np.ones_like()')
printinfo(one_array)


 Create ndarray by np.ones_like()
[[1 1 1]
 [1 1 1]]
shape: (2, 3), size: 6, dtype: int64, dimension: 2


#### Summary
- np.arange()
- np.zeros()
- np.ones()
- np.full()
- np.empty()
- np.*_like()
- ...

### NumPy 의 데이터 타입

#### NumPy 의 데이터 타입

- np.int64 : (64비트) 정수
- np.float64 : (64비트) 실수
- np.complex : 복소수
- np.bool : 불리언(True, False)
- np.object : 파이썬 객체
- np.str : 문자열

#### 정수형(Integer) 데이터 타입
- numpy.int는 음수와 양수를 표현하는 정수형 데이터 타입
- 뒤에 오는 숫자는 bit 의 개수를 의미함 (int8 -> 2^8 = 256 개 만큼의 정수의 표현이 가능)

#### 데이터 타입의 변경

방법1) ndarray 생성시 인자로 dtype 지정하는 방식

In [17]:
# 3차원 ndarray 생성
data = [[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]
arr = np.array(data, dtype=float)

In [18]:
import numpy as np

#dtype 인자 지정을 통한 데이터 타입 변경
data = [1,2,3]
cpx_arr = np.array(data,dtype=np.complex)
str_arr = np.array(data,dtype=np.str)

print('Complex: ', cpx_arr)
print('String: ', str_arr)

Complex:  [1.+0.j 2.+0.j 3.+0.j]
String:  ['1' '2' '3']


방법2) ndarray.astype(dtype)
- ndarray에 저장된 데이터를 주어진 dtype으로 변환해서 반환함
- Paramters : 
  - dtype : 변경하고자 하는 배열의 데이터 타입

#### 샘플 데이터 생성

In [19]:
# 샘플 데이터 생성
origin = np.arange(1, 2, 0.2)
print('\nOriginal data')
print(origin)
print('dtype: ', origin.dtype)


Original data
[1.  1.2 1.4 1.6 1.8]
dtype:  float64


#### .astype() 을 통한 데이터 타입 변경
- astype() 을 활용한 데이터 타입 변경

In [20]:
# astype(dtype)을 활용한 데이터 타입 변경
result = origin.astype(int)
print('\nResult of astype(int)')
print(result)

print('\nOriginal data')
print(origin)


Result of astype(int)
[1 1 1 1 1]

Original data
[1.  1.2 1.4 1.6 1.8]


### Ndarray의 reshape

#### ndarray.shape

#### shape의 변경 사례

사례1) 이미지 데이터를 딥러닝에 적용시

사례2) 머신러닝 알고리즘 적용을 위해 특정 독립변수 컬럼을 선택하여 1차원을 2차원으로 변경하기도 함

#### np.reshape()

np.reshape(array, newshape)
- 기본 데이터는 유지하면서 차원과 shape만을 바꾼 배열을 반환
- Paramter:
  - array : reshape할 ndarray
  - newshape : 변경하고자 하는 shape값(튜플형태)

In [22]:
import numpy as np

# ndarray 속성 출력 함수
def printinfo(arr):
  print(arr)
  print("shape: {}, size: {}, dtype: {}, dimension: {}".format(arr.shape, arr.size, arr.dtype, arr.ndim))

# 샘플 데이터 생성
origin_arr = np.arange(15)
print('\nOriginal ndarray')
printinfo(origin_arr)


Original ndarray
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape: (15,), size: 15, dtype: int64, dimension: 1


- np.reshape()를 통해 2차원 배열로 변경하기

In [26]:
# reshape() 을 활용한 데이터 향상 변경

#reshape_arr = np.reshape(origin_arr, (3,6))
reshape_arr = np.reshape(origin_arr, (3,5))
print('\nReshape ndarray')
printinfo(reshape_arr)


Reshape ndarray
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape: (3, 5), size: 15, dtype: int64, dimension: 2


#### numpy.reshape()

np.reshape(array, newshape)
- 기존 데이터는 유지하면서 차원과 shape만을 바꾼 배열을 반환
- 호출방식(결과는 동일)

  1) np.reshape(origin_arr, (3,5))

  2) origin_arr.reshape((3,5))

#### numpy.reshape(-1, N)

reshape(-1, N)
- 기존 데이터는 유지하면서 , shape을 변경하는 방식
- shape은 주어진 N에 따라 자동으로 추정되어 변경됨
- -1의 자리는 가변적이 됨

- Original ndarray를 1차원에서 2차원으로 변경하기

In [29]:
# origin_arr에 저장된 데이터를 2차원으로 항상 변경
reshape_arr = origin_arr.reshape(-1,1)
print('\nReshape(-1,N) to 2D array')
printinfo(reshape_arr)


Reshape(-1,N) to 2D array
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
shape: (15, 1), size: 15, dtype: int64, dimension: 2


### NumPy 기본 연산

#### NumPy의 주요 특징
- much easier to learn and use
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
-> 연산 속도가 빠르고, 메모리를 효율적으로 사용
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
-> 반복문 작성 필요 없이 N차원의 데이터 배열을 바로 연산할 수 있음

#### NumPy의 기본 연산
- 연산자(+,-,*,/,>,<,==,!=,...)를 이용하여 직관적인 배열 연산 가능
- 모든 연산은 배열의 각 요소별로 적용됨(element-wise)
- 모든 산술 연산 함수는 NumPy 모듈에 구현되어 있음

#### NumPy의 사칙연산
- numpy.add() 또는 + 연산자
- numpy.subtract() 또는 -연산자
- numpy.divide() 또는 / 연산자
- numpy.multiply() 또는 * 연산자

In [30]:
import numpy as np
import time

# 샘플 데이터 생성
a = np.arange(1,10).reshape(3,3)
print('\nA---')
print(a)

b = np.arange(9,0,-1).reshape(3,3)
print('\nB---')
print(b)


A---
[[1 2 3]
 [4 5 6]
 [7 8 9]]

B---
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### NumPy 의 덧셈 연산

np.add(x1,x2)
- 연산자'+'를 사용할 수 있음
- 모든 연산은 배열의 각 요소별로 적용됨(element-wise)

In [31]:
# NumPy의 덧셈연산
result = a+b
print('\nResult of A + B')
print(result)

result = np.add(a, b)
print('\nResult of np.add(a,b)')
print(result)


Result of A + B
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Result of np.add(a,b)
[[10 10 10]
 [10 10 10]
 [10 10 10]]


#### NumPy 의 나눗셈 연산

np.divide(x1,x2)
- 연산자 '/' 를 사용할 수 있음
- 모든 연산은 배열의 각 요소별로 적용됨(element-wise)

In [32]:
# NumPy의 나눗셈 연산
result = a / b
print('\nResult of A / B')
print(result)

result = np.divide(a, b)
print('\nResult of np.divide(a,b)')
print(result)


Result of A / B
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Result of np.divide(a,b)
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


#### NumPy 의 비교 연산
- NumPy의 비교연산은 다음의 연산자를 사용함
  - , >, >= : 크다, 크거나 같다
  - <, <= : 작다, 작거나 같다
  - == : 같다
  - != : 같지 않다

- 비교 연산의 결과는 ? True or False
- 모든 연산은 배열의 각 요소별로 적용됨 (element-wise)

In [33]:
# NumPy 의 비교 연산 (>)
result = a > b
print('\nResult of comparison operator(>)')
print(result)


Result of comparison operator(>)
[[False False False]
 [False False  True]
 [ True  True  True]]


In [34]:
# NumPy 의 비교 연산 (!=)
result = a != b
print('\nResult of comparison operator(!=)')
print(result)


Result of comparison operator(!=)
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]


#### NumPy의 주요 특징
- much easier to learn and use
- 대규모의 고성능 수치 계산을 위한 파이썬 라이브러리
-> 연산 속도가 빠르고, 메모리를 효율적으로 사용
- N차원의 배열을 효율적으로 다룰 수 있는 라이브러리
-> 반복문 작성 필요 없이 N차원의 데이터 배열을 바로 연산할 수 있음

#### NumPy vs Python
- 아래 연산을 python 과 numpy로 구현하면?

arr
[[1 2 3]
 [4 5 6]
 [7 8 9]] + 1

In [43]:
# python

i = 0 
j = 0
for i in range(len(arr)) :
  for j in range(len(arr[i])) : 
    result = arr[i][j] + 1

In [45]:
# numpy
result = arr + 1

TypeError: ignored

#### NumPy vs Python 코드 실행 시간

Q. 동일한 코드를 NumPy와 Python 의 코드 실행 시간의 차이는?

- 비교 코드

총 10,000,000개(0부터 10,000,000까지)의 1차원 데이터에 정수 1을 더하는 연산

- 코드 실행 시간 측정을 위해 Python의 Time 모듈 사용
  - import time
  - time.time() : 현재 시점의 시간(초 단위)

In [46]:
import time

# Python 코드 실행 시간 측정하기
python_arr = range(10000000)
start = time.time()
for i in python_arr:
  i +1
stop = time.time()
print("\nPython(ms):", (stop - start)*1000)


Python(ms): 952.1801471710205


In [47]:
# NumPy 코드 실행 시간 측정하기
numpy_arr = np.arange(10000000)
start = time.time()
numpy_arr +1 
stop = time.time()
print("NumPy(ms):", (stop-start)*1000)

NumPy(ms): 38.16390037536621


#### NumPy 의 기타 연산

다차원의 ndarray에 적용할 수 있는 고성능의 다양한 연산 함수 제공
- 제곱연산 : numpy.square() 또는 **2 연산자
- 제곱근(square root) 연산 : numpy.sqrt()
- 지수 연산 : numpy.exp()
- 삼각함수 : numpy.sin(), numpy.cos()

#### Tip! 공식 사이트 활용

1) https://numpy.org/ 접속

2) 화면 상단의 Documentation 메뉴 클릭

3) 검색창에 키워드 검색 : 제곱근 연산 : numpy.sqrt

#### Tip! Help() 함수 활용
help(command)

In [48]:
# Tip ! Help() 함수의 활용
print('\nHelp on numpy.sqrt()')
help(np.sqrt)


Help on numpy.sqrt()
Help on ufunc object:

sqrt = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |

### NumPy 집계 함수

#### NumPy 의 집계 함수
- 집계 함수(Aggregate Functions)란?
  - 데이터를 종합하여 특정 연산을 적용하는 함수들을 총칭

- 합계 : sum()
- 최소값 : min()
- 최대값 : max()
- 누적합계 : cumsum()
- 평균 : mean()
- 중앙값: median()
- 상관계수 : corrcoef()
- 표준편차 : std()
- 고유값 : unique()

#### 데이터의 집계 방향
- 집계 함수의 기능 이해와 사용법은 매우 단순함
  - 방법 (1)
  array.sum()
  - 방법 (2)
  np.sum(array)

- 중요한 것은 데이터의 집계 방향을 지정해야함
  - axis = None(default)
  - axis = 0
  - axis = 1

In [49]:
import numpy as np

# 샘플 데이터 생성
sample = np.arange(1, 10).reshape(3,3)
print('Sample')
print(sample)

Sample
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 데이터의 집계 방향(axis=None)
axis = None(default)
- 대상 ndarray의 모든 요소가 연산 대상이 됨
- Default 값이므로 집계 함수 호출시 생략 가능

In [50]:
# axis = None 실습 (default)
print('\n[Case-1]axis = None')
print('sum : ', sample.sum())
print('mean : ', sample.mean())
print('std : ', sample.std())
print('max : ', sample.max())
print('min : ', sample.min())


[Case-1]axis = None
sum :  45
mean :  5.0
std :  2.581988897471611
max :  9
min :  1


#### 데이터의 집계 방향 (axis = 0)
axis = 0
- 열을 기준으로 동일 인덱스의 요소를 그룹으로 연산함

In [51]:
# axis = 0 실습
print('\n[Case-2]axis = 0')
print('sum : ', sample.sum(axis = 0))
print('mean : ', sample.mean(axis = 0))
print('std : ', sample.std(axis = 0))
print('max : ', sample.max(axis = 0))
print('min : ', sample.min(axis = 0))


[Case-2]axis = 0
sum :  [12 15 18]
mean :  [4. 5. 6.]
std :  [2.44948974 2.44948974 2.44948974]
max :  [7 8 9]
min :  [1 2 3]


#### 데이터의 집계 방향 (axis = 1)
axis = 1
- 행을 기준으로 동일 인덱스의 요소를 그룹으로 연산함

In [53]:
# axis = 1 실습 (default)
print('\n[Case-3]axis = 1')
print('sum : ', sample.sum(axis = 1))
print('mean : ', sample.mean(axis = 1))
print('std : ', sample.std(axis = 1))
print('max : ', sample.max(axis = 1))
print('min : ', sample.min(axis = 1))


[Case-3]axis = 1
sum :  [ 6 15 24]
mean :  [2. 5. 8.]
std :  [0.81649658 0.81649658 0.81649658]
max :  [3 6 9]
min :  [1 4 7]


#### 데이터의 집계 방향이 왜 중요할까?